# Copyright (c) 2010 ThoughtWorks Inc. (http://thoughtworks.com)
# Licenced under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0.txt)

require 'rake/testtask'
require 'rake/rdoctask'

include FileUtils

desc "run all unit tests"
task :test do  
  Rake::TestTask.new do |t|
    rm_rf('tmp')
    t.test_files = FileList['tests/unit/**/*_test.rb']
    t.verbose = true
  end
end

desc "default task"
task :default => [:test]
